/** FireGuard visual system: the live overview keeps the reference’s asymmetric command surface while its metrics and priority queue come from the operational database. */
import React from "react";
import { ArrowUpRight, Building2, CalendarDays, ChevronDown, CircleAlert, Clock3, MapPin, Plus, ShieldAlert, SlidersHorizontal, TrendingUp, Wrench } from "lucide-react";
import { Link, useLocation } from "wouter";
import { ActionButton, CorePageState, LoadSuccessCue, MetricDelta, OpenIcon, PageHeader, StatusBadge, SurfaceTitle, useLoadSuccessCue } from "@/components/FireGuardUI";
import { InteractiveBarChart, InteractiveLineChart, InteractiveMeter } from "@/components/InteractiveOperationsCharts";
import { formatOperationalDate, useFireguardPermissions, useFireguardWorkspace } from "@/hooks/useFireguardData";
import { buildEvidenceProgressSeries, buildScheduledWorkOrderVolumeSeries, buildSiteCoverageSeries } from "@/lib/visualizationSeries";
import { getWorkspaceHealth, type WorkspaceHealthKey } from "@/lib/workspaceHealth";
import { getWhatChanged, getWhatChangedEmptyCopy, type FireGuardChangeRole } from "@/lib/whatChanged";

const exceptionTone = (severity: "high" | "medium" | "low") => severity === "high" ? "risk" : severity === "medium" ? "warning" : "neutral" as const;
export default function Dashboard() {
  const [, setLocation] = useLocation();
  const { data, isLoading, error, refetch } = useFireguardWorkspace();
  const { data: permissions } = useFireguardPermissions();
  const loadSuccessPhase = useLoadSuccessCue(isLoading || Boolean(error));
  if (isLoading) return <CorePageState state="loading" title="Loading live operations" description="Pressurising the latest readiness view." />;
  if (error || !data) return <CorePageState state="error" title="Operations workspace unavailable" description="Try again to recover the latest readiness view." actionLabel="Retry workspace" onAction={() => void refetch()} />;
  const completion = Math.round(data.workOrders.reduce((sum, work) => sum + work.evidenceProgress, 0) / Math.max(1, data.workOrders.length));
  const evidenceSeries = buildEvidenceProgressSeries(data.workOrders);
  const workVolumeSeries = buildScheduledWorkOrderVolumeSeries(data.workOrders);
  const siteCoverageSeries = buildSiteCoverageSeries(data.metrics.siteCount, data.metrics.readySiteCount);
  const workspaceHealth = getWorkspaceHealth(data);
  const recentChanges = getWhatChanged(data, permissions?.role as FireGuardChangeRole | undefined);
  const healthIcons: Record<WorkspaceHealthKey, typeof Building2> = { clients: Building2, sites: MapPin, workOrders: Wrench, exceptions: CircleAlert };
  return <div className="page-enter"><LoadSuccessCue phase={loadSuccessPhase} label="Operations live" detail="Latest readiness signals are ready" />
    <PageHeader eyebrow="Overview" title="Safety overview" description={data.isDemo ? "Live data flow using clearly labelled FireGuard demonstration records. Replace these records with operational account data as your team is ready." : "A clear view of live site readiness, work underway, and the few items that need an owner."}>
      <ActionButton tone="quiet" icon={SlidersHorizontal} onClick={() => setLocation("/exceptions")}>Risk filters</ActionButton><ActionButton tone="quiet" icon={CalendarDays}>Current period <ChevronDown size={13} /></ActionButton><ActionButton icon={Plus} onClick={() => setLocation("/service")}>Log service</ActionButton>
    </PageHeader>
    <section className="dashboard-grid" aria-label="Operations overview">
      <article className="surface-card brief-card"><div><span className="brief-index"><CircleAlert size={12} />Live readiness brief</span><div className="brief-main"><h2 className="brief-headline">{data.metrics.openExceptionCount === 0 ? "Every site ready for inspection." : `${data.metrics.openExceptionCount} items need a clear owner.`}</h2><p className="brief-copy">{data.metrics.overdueExceptionCount > 0 ? `${data.metrics.overdueExceptionCount} exception${data.metrics.overdueExceptionCount === 1 ? " is" : "s are"} overdue. Open the priority queue to keep readiness on plan.` : "Your current records are on plan. Continue the scheduled checks to maintain site readiness."}</p></div></div><div className="brief-footer"><div className="brief-footer-top"><span>Next inspection</span><span>{formatOperationalDate(data.sites[0]?.nextInspectionAt)}</span></div><div className="mini-divider" /><p>{data.sites[0]?.name ?? "No sites scheduled"} · operational records are live.</p></div></article>
      <article className="surface-card chart-card activity-card"><SurfaceTitle title="Readiness activity" subtitle="Live scheduled work-order volume" action={<OpenIcon />} /><div className="value-large">{data.workOrders.length}<span className="metric-unit">jobs</span></div><MetricDelta><TrendingUp size={12} />{data.workOrders.filter(work => work.status !== "complete").length} active work orders</MetricDelta><InteractiveLineChart ariaLabel="Scheduled work-order volume by date" data={workVolumeSeries} /></article>
      <article className="surface-card chart-card signal-card"><SurfaceTitle title="Compliance pulse" subtitle="Across managed sites" action={<OpenIcon />} /><div className="value-large">{Math.round((data.metrics.readySiteCount / Math.max(1, data.metrics.siteCount)) * 100)}<span className="metric-unit">%</span></div><MetricDelta>{data.metrics.readySiteCount} sites ready for inspection</MetricDelta><div className="signal-meter"><InteractiveMeter label="Ready" value={data.metrics.readySiteCount} total={data.metrics.siteCount} /><InteractiveMeter label="Exceptions" value={data.metrics.openExceptionCount} total={data.metrics.siteCount} tone="risk" /></div></article>
      <article className="signal-tile"><div><span className="soft-label">Service capacity</span><strong>{data.workOrders.filter(work => work.status !== "complete").length} active work orders</strong><p>Live database state updates as teams start, submit, and review their scheduled work.</p></div><div className="signal-tile-foot"><span>{data.metrics.siteCount} sites tracked</span><span>Live</span></div></article>
      <article className="surface-card chart-card spend-card"><SurfaceTitle title="Evidence completion" subtitle="Inspect the live progress for scheduled work" action={<OpenIcon />} /><div className="spend-layout"><div><div className="value-large">{completion}<span className="metric-unit">%</span></div><MetricDelta><TrendingUp size={12} />{data.metrics.completedWorkOrders} jobs closed</MetricDelta><div className="spend-stat-grid"><div className="tiny-stat"><strong>{data.workOrders.filter(work => work.status === "in_progress").length}</strong><span>active</span></div><div className="tiny-stat"><strong>{data.workOrders.filter(work => work.status === "awaiting_review").length}</strong><span>review</span></div></div></div><InteractiveLineChart ariaLabel="Scheduled work evidence progress" data={evidenceSeries} valueSuffix="%" /></div></article>
    </section>
    <section className="surface-card workspace-health-panel" aria-labelledby="workspace-health-title"><div className="workspace-health-intro"><span className="soft-label">Workspace health</span><div className="workspace-health-heading"><div><h2 id="workspace-health-title">Record coverage</h2><p>{workspaceHealth.isEmpty ? "No client, site, work-order, or exception records are available yet. Add operational records when your team is ready." : `${workspaceHealth.totalCount} operational records are currently available across the FireGuard workspace.`}</p></div><StatusBadge tone={workspaceHealth.isEmpty ? "neutral" : workspaceHealth.demoCount > 0 ? "warning" : "good"}>{workspaceHealth.isEmpty ? "Empty workspace" : workspaceHealth.demoCount > 0 ? `${workspaceHealth.demoCount} demo labelled` : "Operational data"}</StatusBadge></div></div><div className="workspace-health-metrics" aria-label="Workspace record counts">{workspaceHealth.items.map(item => { const Icon = healthIcons[item.key]; return <Link className="workspace-health-metric" href={item.href} key={item.key} aria-label={`View ${item.count} ${item.label.toLowerCase()} in the operational list`}><span><Icon size={15} />{item.label}</span><strong>{item.count}</strong><small>{item.count === 0 ? "No records" : item.demoCount > 0 ? `${item.demoCount} demonstration record${item.demoCount === 1 ? "" : "s"}` : "Operational records"}</small><em>Open list <ArrowUpRight size={12} /></em></Link>; })}</div></section>
    <section className="surface-card what-changed-panel" aria-labelledby="what-changed-title"><SurfaceTitle title="What changed" subtitle={permissions?.role ? `Updates visible to your ${permissions.role} role` : "Checking your update scope"} action={<Clock3 size={16} color="#817c76" />} />{recentChanges.length ? <div className="what-changed-list">{recentChanges.map(item => <div className="what-changed-row" key={item.id}><span className={`what-changed-icon is-${item.kind}`} aria-hidden="true">{item.kind === "risk" ? <ShieldAlert size={15} /> : <Wrench size={15} />}</span><div><strong>{item.title}</strong><p>{item.summary}</p></div><StatusBadge tone={item.tone}>{item.kind === "risk" ? "Risk update" : "Work update"}</StatusBadge></div>)}</div> : <CorePageState compact state="empty" title="No recent operational changes" description={getWhatChangedEmptyCopy(permissions?.role as FireGuardChangeRole | undefined)} />}</section>
    <section className="queue-grid"><article className="surface-card queue-card"><SurfaceTitle title="Priority queue" subtitle="Live exception records requiring a decision" action={<button className="quiet-button" onClick={() => setLocation("/exceptions")}>View all</button>} />{data.exceptions.slice(0, 3).map(item => <div className="queue-item" key={item.id}><span className={`queue-dot ${item.severity === "high" ? "" : "is-good"}`} /><div><strong>{item.title}</strong><p>{item.clientName} · {item.siteName}</p></div><StatusBadge tone={exceptionTone(item.severity)}>{item.status === "acknowledged" ? "Owned" : item.severity === "high" ? "High risk" : "Review"}</StatusBadge></div>)}</article><article className="surface-card chart-card map-card"><SurfaceTitle title="Coverage today" subtitle={`${data.metrics.siteCount} managed sites`} action={<button className="quiet-button coverage-map-action" onClick={() => setLocation("/clients/map")}>Open live map</button>} /><InteractiveBarChart ariaLabel="Live site readiness coverage" data={siteCoverageSeries} /></article></section>
  </div>;
}
