/** FireGuard visual system: reports export current database rows to CSV and retain a server-side audit record of each requested export. */
import React from "react";
import { CalendarDays, Download, FileBarChart, Plus } from "lucide-react";
import { toast } from "sonner";
import { InteractiveBarChart } from "@/components/InteractiveOperationsCharts";
import { ActionButton, PageHeader, SurfaceTitle } from "@/components/FireGuardUI";
import { useFireguardPermissions, useFireguardWorkspace } from "@/hooks/useFireguardData";
import { buildWorkOrderStatusSeries } from "@/lib/visualizationSeries";
import { trpc } from "@/lib/trpc";

export default function Reports() {
  const { data, isLoading, error } = useFireguardWorkspace(); const { data: permissions } = useFireguardPermissions();
  const exporter = trpc.fireguard.reports.generate.useMutation({ onSuccess: result => { const url = URL.createObjectURL(new Blob([result.csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = result.filename; link.click(); URL.revokeObjectURL(url); toast.success(`${result.rowCount} current records exported.`); }, onError: error => toast.error(error.message) });
  const exportReport = (type: "readiness" | "service" | "exceptions") => permissions?.canManageOperations ? exporter.mutate({ type }) : toast.error("Manager access is required to export operational reports.");
  if (isLoading) return <div className="surface-card summary-card">Loading report data…</div>; if (error || !data) return <div className="surface-card summary-card">Report data is unavailable.</div>;
  const statusSeries = buildWorkOrderStatusSeries(data.workOrders);
  return <div className="page-enter"><PageHeader eyebrow="Reports" title="Operational reporting" description="Generate CSV exports directly from current FireGuard records. Each export retains a durable audit entry."><ActionButton tone="quiet" icon={CalendarDays} onClick={() => toast("Reporting uses the current operational dataset.")}>Current data</ActionButton><ActionButton icon={Download} onClick={() => exportReport("readiness")}>Export readiness</ActionButton></PageHeader><section className="report-grid"><article className="surface-card chart-card report-card"><SurfaceTitle title="Work-order status" subtitle="Live work-order distribution" action={<FileBarChart size={17} color="#c7d59c" />} /><InteractiveBarChart ariaLabel="Live work-order status distribution" data={statusSeries} /></article><aside className="side-summary"><article className="surface-card summary-card"><SurfaceTitle title="Readiness score" subtitle="Current site state" /><div className="value-large">{Math.round((data.metrics.readySiteCount / Math.max(1, data.metrics.siteCount)) * 100)}%</div><div style={{ marginTop: 12 }} className="report-note"><strong className="soft-label">Data source</strong><p>{data.metrics.siteCount} sites and {data.workOrders.length} work orders currently included.</p></div></article><article className="surface-card summary-card"><SurfaceTitle title="Report library" subtitle="Live CSV exports" /><div className="summary-row"><span>Client readiness</span><button className="quiet-button" onClick={() => exportReport("readiness")}>Create</button></div><div className="summary-row"><span>Service completion</span><button className="quiet-button" onClick={() => exportReport("service")}>Create</button></div><div className="summary-row"><span>Exception digest</span><button className="quiet-button" onClick={() => exportReport("exceptions")}>Create</button></div></article></aside></section><section className="queue-grid"><article className="surface-card report-card"><SurfaceTitle title="Inspection outcomes" subtitle="Current operational dataset" /><div className="summary-row"><span>Sites ready</span><strong>{data.metrics.readySiteCount}</strong></div><div className="summary-row"><span>Open exceptions</span><strong>{data.metrics.openExceptionCount}</strong></div><div className="summary-row"><span>Overdue items</span><strong style={{ color: "#d94a3a" }}>{data.metrics.overdueExceptionCount}</strong></div></article><article className="signal-tile"><div><span className="soft-label">Access boundary</span><strong>{permissions?.canManageOperations ? "Exports enabled" : "Manager approval required"}</strong><p>Report download actions are enforced by the server, not only hidden in the interface.</p></div><ActionButton tone="dark" icon={Plus} onClick={() => exportReport("service")}>Create service report</ActionButton></article></section></div>;
}
