/** FireGuard visual system: reviewers approve the evidence records that field teams have submitted into the live work-order queue. */
import React from "react";
import { ClipboardCheck, FileCheck2, Filter, Plus, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { ActionButton, CorePageState, LoadSuccessCue, PageHeader, StatusBadge, useLoadSuccessCue } from "@/components/FireGuardUI";
import { useFireguardPermissions, useFireguardWorkspace } from "@/hooks/useFireguardData";
import { trpc } from "@/lib/trpc";

export default function Reviews() {
  const utils = trpc.useUtils(); const { data, isLoading, error, refetch } = useFireguardWorkspace(); const { data: permissions } = useFireguardPermissions(); const loadSuccessPhase = useLoadSuccessCue(isLoading || Boolean(error));
  const approve = trpc.fireguard.workOrders.approve.useMutation({ onSuccess: () => { toast.success("Evidence approved and work order closed."); utils.fireguard.workspace.invalidate(); }, onError: error => toast.error(error.message) });
  if (isLoading) return <CorePageState state="loading" title="Loading evidence queue" description="Checking submitted work for reviewer decisions." />; if (error || !data) return <CorePageState state="error" title="Evidence records unavailable" description="Try again to recover the review queue." actionLabel="Retry review queue" onAction={() => void refetch()} />;
  const reviewRows = data.workOrders.filter(work => work.status === "awaiting_review");
  return <div className="page-enter"><LoadSuccessCue phase={loadSuccessPhase} label="Review queue ready" detail="Submitted evidence is ready for accountable decisions" /><PageHeader eyebrow="Review" title="Evidence review" description="Only reviewers, managers, and administrators can approve submitted work and close the operational record."><ActionButton tone="quiet" icon={Filter} onClick={() => toast("Showing items awaiting review.")}>Awaiting review</ActionButton><ActionButton icon={Plus} onClick={() => toast("Evidence collection is recorded against each work order.")}>Request evidence</ActionButton></PageHeader><section className="content-grid"><article className="review-list">{reviewRows.length ? reviewRows.map((work, index) => { const Icon = index % 2 ? ClipboardCheck : FileCheck2; return <article className="surface-card review-item" key={work.id}><span className="review-icon"><Icon size={20} /></span><div><h2>{work.title}</h2><p>{work.clientName} · {work.siteName}. Evidence package is complete and ready for a reviewer decision.</p><div style={{ marginTop: 10 }}><StatusBadge tone="good">Evidence complete</StatusBadge></div></div><div className="review-action">{permissions?.canReviewEvidence ? <ActionButton tone="dark" onClick={() => approve.mutate({ id: work.id })}>Approve</ActionButton> : <StatusBadge tone="warning">Reviewer only</StatusBadge>}</div></article>; }) : <CorePageState state="empty" title="Review queue clear" description="Submitted evidence will appear here for reviewer approval." compact />}</article><aside className="side-summary"><article className="surface-card summary-card"><h2 className="card-title">Review queue</h2><p className="card-subtitle">Current database state</p><div className="summary-row"><span>Ready to approve</span><strong>{reviewRows.length}</strong></div><div className="summary-row"><span>Active field work</span><strong>{data.workOrders.filter(work => work.status === "in_progress").length}</strong></div><div className="summary-row"><span>Blocked evidence</span><strong style={{ color: "#d94a3a" }}>{data.workOrders.filter(work => work.status === "blocked").length}</strong></div></article><article className="surface-card image-surface"><div><h2 className="card-title">Evidence health</h2><p>Evidence approval is a role-protected change to a live work-order record.</p></div></article><article className="surface-card summary-card"><div style={{ display: "flex", gap: 8, alignItems: "center" }}><ShieldCheck size={17} color="#5aad90" /><h2 className="card-title">Access guard</h2></div><p className="page-description">Your current role is <strong>{permissions?.role ?? "…"}</strong>.</p></article></aside></section></div>;
}
