/** Fictional FireGuard demonstration records. All names, schedules, and incidents below are illustrative only and are never mixed with live operations. */
export const kigaliDemoClients = [
  { name: "Kigali Heights Retail · DEMO", portfolioOwnerName: "Aline N.", readinessStatus: "review" as const },
  { name: "Nyarutarama Offices · DEMO", portfolioOwnerName: "Emmanuel K.", readinessStatus: "ready" as const },
  { name: "Kacyiru Civic Campus · DEMO", portfolioOwnerName: "Diane M.", readinessStatus: "risk" as const },
  { name: "Kimihurura Hospitality · DEMO", portfolioOwnerName: "Patrick R.", readinessStatus: "review" as const },
  { name: "Remera Sports Quarter · DEMO", portfolioOwnerName: "Aline N.", readinessStatus: "ready" as const },
  { name: "Gikondo Trade Centre · DEMO", portfolioOwnerName: "Emmanuel K.", readinessStatus: "risk" as const },
  { name: "Nyamirambo Market Group · DEMO", portfolioOwnerName: "Diane M.", readinessStatus: "review" as const },
  { name: "Kimironko Logistics · DEMO", portfolioOwnerName: "Patrick R.", readinessStatus: "ready" as const },
  { name: "Kibagabaga Residences · DEMO", portfolioOwnerName: "Aline N.", readinessStatus: "review" as const },
  { name: "Kanombe Airside Services · DEMO", portfolioOwnerName: "Emmanuel K.", readinessStatus: "risk" as const },
  { name: "Muhima Learning Hub · DEMO", portfolioOwnerName: "Diane M.", readinessStatus: "ready" as const },
  { name: "Kiyovu Professional Centre · DEMO", portfolioOwnerName: "Patrick R.", readinessStatus: "review" as const },
];

export const kigaliDemoSites = [
  ["Kigali Heights Retail · DEMO", "Kigali Heights · Main Arcade", "Kigali Heights, KN 5 Rd", "review", -1.9448, 30.0611, "Retail alarm verification", "Alarm system", "scheduled", 68, 1, 3, "Escape-route sign-off incomplete", "medium"],
  ["Kigali Heights Retail · DEMO", "Kigali Heights · Parking Deck", "Kigali Heights, KN 5 Rd", "ready", -1.9455, 30.0605, "Vehicle-bay extinguisher check", "Extinguishers", "in_progress", 45, 2, 4, null, null],
  ["Nyarutarama Offices · DEMO", "Nyarutarama · Block A", "KG 9 Ave, Nyarutarama", "ready", -1.9346, 30.0951, "Quarterly fire-door survey", "Fire doors", "scheduled", 72, 3, 5, null, null],
  ["Nyarutarama Offices · DEMO", "Nyarutarama · Annex", "KG 9 Ave, Nyarutarama", "review", -1.9338, 30.0962, "Emergency lighting annual test", "Emergency lighting", "awaiting_review", 100, -1, 2, "Evidence pack needs reviewer approval", "low"],
  ["Kacyiru Civic Campus · DEMO", "Kacyiru · East Building", "KG 7 Ave, Kacyiru", "risk", -1.9357, 30.0735, "Suppression valve maintenance", "Sprinkler systems", "blocked", 18, 0, 1, "Isolation valve access window expired", "high"],
  ["Kacyiru Civic Campus · DEMO", "Kacyiru · Records Wing", "KG 7 Ave, Kacyiru", "review", -1.9366, 30.0744, "Archive room smoke-detector test", "Detection", "scheduled", 58, 4, 6, null, null],
  ["Kimihurura Hospitality · DEMO", "Kimihurura · Guest House", "KG 670 St, Kimihurura", "review", -1.9490, 30.0884, "Kitchen suppression inspection", "Kitchen suppression", "scheduled", 36, 1, 2, "Kitchen hood access requires a confirmed slot", "medium"],
  ["Kimihurura Hospitality · DEMO", "Kimihurura · Events Annex", "KG 670 St, Kimihurura", "ready", -1.9501, 30.0891, "Events-floor extinguisher service", "Extinguishers", "in_progress", 61, 2, 4, null, null],
  ["Remera Sports Quarter · DEMO", "Remera · Training Pavilion", "KG 17 Ave, Remera", "ready", -1.9570, 30.1110, "Crowd-route emergency lighting check", "Emergency lighting", "scheduled", 84, 5, 7, null, null],
  ["Remera Sports Quarter · DEMO", "Remera · Equipment Store", "KG 17 Ave, Remera", "review", -1.9580, 30.1117, "Equipment-store detection test", "Detection", "scheduled", 52, 3, 5, null, null],
  ["Gikondo Trade Centre · DEMO", "Gikondo · Warehouse 4", "KK 15 Rd, Gikondo", "risk", -1.9830, 30.0945, "Warehouse hydrant inspection", "Hydrant systems", "blocked", 12, -1, 1, "Hydrant pressure record is overdue", "high"],
  ["Gikondo Trade Centre · DEMO", "Gikondo · Loading Court", "KK 15 Rd, Gikondo", "review", -1.9821, 30.0958, "Loading-court evacuation route review", "Evacuation routes", "scheduled", 47, 4, 6, null, null],
  ["Nyamirambo Market Group · DEMO", "Nyamirambo · Market Hall", "KN 20 Ave, Nyamirambo", "review", -1.9730, 30.0429, "Market-hall extinguisher verification", "Extinguishers", "scheduled", 63, 2, 4, "Two extinguishers need serial-number reconciliation", "medium"],
  ["Nyamirambo Market Group · DEMO", "Nyamirambo · Food Court", "KN 20 Ave, Nyamirambo", "ready", -1.9721, 30.0438, "Food-court suppression check", "Kitchen suppression", "awaiting_review", 100, 0, 2, null, null],
  ["Kimironko Logistics · DEMO", "Kimironko · Dispatch Yard", "KG 11 Ave, Kimironko", "ready", -1.9430, 30.1245, "Dispatch-yard smoke detector service", "Detection", "scheduled", 76, 6, 8, null, null],
  ["Kimironko Logistics · DEMO", "Kimironko · Cold Store", "KG 11 Ave, Kimironko", "review", -1.9420, 30.1250, "Cold-store emergency signage audit", "Evacuation routes", "in_progress", 39, 1, 3, null, null],
  ["Kibagabaga Residences · DEMO", "Kibagabaga · Tower 1", "KG 303 St, Kibagabaga", "review", -1.9305, 30.1126, "Residential riser inspection", "Riser systems", "scheduled", 55, 3, 5, null, null],
  ["Kibagabaga Residences · DEMO", "Kibagabaga · Tower 2", "KG 303 St, Kibagabaga", "ready", -1.9296, 30.1134, "Lobby alarm panel inspection", "Alarm system", "scheduled", 81, 5, 7, null, null],
  ["Kanombe Airside Services · DEMO", "Kanombe · Operations Office", "KK 15 Rd, Kanombe", "risk", -1.9660, 30.1374, "Operations-office alarm test", "Alarm system", "blocked", 24, 0, 1, "Control-panel fault requires a technician visit", "high"],
  ["Kanombe Airside Services · DEMO", "Kanombe · Service Bay", "KK 15 Rd, Kanombe", "review", -1.9651, 30.1382, "Service-bay foam unit check", "Extinguishers", "scheduled", 49, 4, 6, null, null],
  ["Muhima Learning Hub · DEMO", "Muhima · Learning Centre", "KN 1 Ave, Muhima", "ready", -1.9390, 30.0490, "Classroom emergency light inspection", "Emergency lighting", "scheduled", 88, 6, 8, null, null],
  ["Kiyovu Professional Centre · DEMO", "Kiyovu · South Terrace", "KN 3 Rd, Kiyovu", "review", -1.9515, 30.0553, "Terrace office evacuation review", "Evacuation routes", "scheduled", 41, 2, 4, "Assembly-point sign requires replacement", "low"],
] as const;
